//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCPower.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCPowerEntities : DbContext
    {
        public PCPowerEntities()
            : base("name=PCPowerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Order>()
                .HasOptional(j => j.Receipts)
                .WithMany()
                .WillCascadeOnDelete(true);
            modelBuilder.Entity<Order>()
                .HasOptional(j => j.Shop)
                .WithMany()
                .WillCascadeOnDelete(true);


            modelBuilder.Entity<Receipt>()
                .HasKey(t => t.fk_Order_Id);

            modelBuilder.Entity<Receipt>()
                .HasOptional(j => j.Orders)
                .WithRequired()
                .WillCascadeOnDelete(true);
 
            modelBuilder.Entity<Order>()
                .HasOptional(j => j.Parts)
                .WithMany()
                .WillCascadeOnDelete(true);
            modelBuilder.Entity<Order>()
                .HasOptional(j => j.Repairs)
                .WithMany()
                .WillCascadeOnDelete(true);
            base.OnModelCreating(modelBuilder);
            
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Build> Builds { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Computer> Computers { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<Repair> Repairs { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<Transfer> Transfers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
    }
}
