//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCPower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Text { get; set; }
        public int fk_Chat_Id { get; set; }
        public int fk_Sender_Id { get; set; }
        public int fk_Reciever_Id { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
