//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCPower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int Id { get; set; }
        public Nullable<int> fk_Repair_Id { get; set; }
        public Nullable<int> fk_Shop_Id { get; set; }
        public Nullable<int> fk_Receipt_Id { get; set; }
        public int fk_Client_Id { get; set; }
        public Nullable<int> fk_Part_Id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Part Part { get; set; }
        public virtual Receipt Receipt { get; set; }
        public virtual Repair Repair { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
