//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCPower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Part()
        {
            this.Builds = new HashSet<Build>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public string Specification { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<int> fk_Warehouse_Id { get; set; }
        public Nullable<int> fk_Transfer_Id { get; set; }
        public int fk_Order_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Build> Builds { get; set; }
        public virtual Order Order { get; set; }
        public virtual Transfer Transfer { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
